import 'dart:convert';
import 'dart:io';

void main() async {
  print('🌍 Odyssey Auto-Translator');
  
  final translations = <String, String>{
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'edit': 'Editar',
    'add': 'Adicionar',
    'confirm': 'Confirmar',
    'close': 'Fechar',
    'today': 'Hoje',
    'yesterday': 'Ontem',
    'tomorrow': 'Amanhã',
    'thisWeek': 'Esta Semana',
    'thisMonth': 'Este Mês',
    'goodMorning': 'Bom dia',
    'goodAfternoon': 'Boa tarde',
    'goodEvening': 'Boa noite',
    'mood': 'Humor',
    'howAreYou': 'Como você está?',
    'howAreYouFeeling': 'Como você está se sentindo?',
    'recordMood': 'Registrar Humor',
    'veryGood': 'Muito bem',
    'good': 'Bem',
    'neutral': 'Neutro',
    'bad': 'Mal',
    'veryBad': 'Muito mal',
    'excellent': 'Excelente',
    'great': 'Ótimo',
    'fair': 'Regular',
    'terrible': 'Péssimo',
    'happy': 'Feliz',
    'sad': 'Triste',
    'anxious': 'Ansioso',
    'calm': 'Calmo',
    'stressed': 'Estressado',
    'excited': 'Animado',
    'tired': 'Cansado',
    'motivated': 'Motivado',
    'bored': 'Entediado',
    'relaxed': 'Relaxado',
    'focused': 'Focado',
    'productive': 'Produtivo',
    'energetic': 'Energético',
    'sleepy': 'Sonolento',
    'grateful': 'Grato',
    'habit': 'Hábito',
    'habits': 'Hábitos',
    'newHabit': 'Novo Hábito',
    'createHabit': 'Criar Hábito',
    'editHabit': 'Editar Hábito',
    'streak': 'Sequência',
    'record': 'Recorde',
    'dailyGoal': 'Meta Diária',
    'weeklyGoal': 'Meta Semanal',
    'frequency': 'Frequência',
    'reminder': 'Lembrete',
    'reminders': 'Lembretes',
    'task': 'Tarefa',
    'tasks': 'Tarefas',
    'newTask': 'Nova Tarefa',
    'createTask': 'Criar Tarefa',
    'editTask': 'Editar Tarefa',
    'myTasks': 'Minhas Tarefas',
    'noTasks': 'Nenhuma tarefa',
    'noTasksPending': 'Nenhuma tarefa pendente',
    'noTasksCompleted': 'Nenhuma tarefa concluída',
    'addTaskToStart': 'Adicione uma tarefa para começar',
    'completeTasksToSee': 'Complete suas tarefas para vê-las aqui',
    'taskTitle': 'O que você precisa fazer?',
    'dueDate': 'Data de Vencimento',
    'category': 'Categoria',
    'categories': 'Categorias',
    'priority': 'Prioridade',
    'priorityHigh': 'Alta',
    'priorityMedium': 'Média',
    'priorityLow': 'Baixa',
    'all': 'Todas',
    'pending': 'Pendentes',
    'completed': 'Concluídas',
    'overdue': 'Atrasadas',
    'note': 'Nota',
    'notes': 'Notas',
    'newNote': 'Nova Nota',
    'createNote': 'Criar Nota',
    'editNote': 'Editar Nota',
    'myNotes': 'Minhas Notas',
    'noNotes': 'Nenhuma nota',
    'quickNote': 'Nota Rápida',
    'title': 'Título',
    'content': 'Conteúdo',
    'description': 'Descrição',
    'timer': 'Timer',
    'focus': 'Foco',
    'breakTime': 'Pausa',
    'shortBreak': 'Pausa Curta',
    'longBreak': 'Pausa Longa',
    'start': 'Iniciar',
    'pause': 'Pausar',
    'stop': 'Parar',
    'restart': 'Reiniciar',
    'resume': 'Retomar',
    'session': 'Sessão',
    'sessions': 'Sessões',
    'focusTime': 'Tempo de Foco',
    'timerActive': 'Timer Ativo',
    'inBackground': 'em background',
    'continueInBackground': 'Continuar em background',
    'backToTimer': 'Voltar ao timer',
    'endSession': 'Encerrar sessão',
    'pauseTimer': 'Pausar timer',
    'activity': 'Atividade',
    'activities': 'Atividades',
    'history': 'Histórico',
    'statistics': 'Estatísticas',
    'library': 'Biblioteca',
    'book': 'Livro',
    'books': 'Livros',
    'newBook': 'Novo Livro',
    'addBook': 'Adicionar Livro',
    'reading': 'Lendo',
    'read': 'Lido',
    'wantToRead': 'Quero Ler',
    'abandoned': 'Abandonado',
    'author': 'Autor',
    'pages': 'Páginas',
    'progress': 'Progresso',
    'rating': 'Avaliação',
    'review': 'Resenha',
    'genre': 'Gênero',
    'myBooks': 'Meus Livros',
    'noBooks': 'Nenhum livro',
    'settings': 'Configurações',
    'preferences': 'Preferências',
    'theme': 'Tema',
    'light': 'Claro',
    'dark': 'Escuro',
    'automatic': 'Automático',
    'language': 'Idioma',
    'notifications': 'Notificações',
    'sounds': 'Sons',
    'vibration': 'Vibração',
    'backup': 'Backup',
    'restore': 'Restaurar',
    'account': 'Conta',
    'profile': 'Perfil',
    'about': 'Sobre',
    'help': 'Ajuda',
    'version': 'Versão',
    'rateApp': 'Avaliar App',
    'privacy': 'Privacidade',
    'level': 'Nível',
    'points': 'Pontos',
    'achievement': 'Conquista',
    'achievements': 'Conquistas',
    'unlocked': 'Desbloqueado',
    'locked': 'Bloqueado',
    'success': 'Sucesso',
    'error': 'Erro',
    'warning': 'Aviso',
    'loading': 'Carregando',
    'pleaseWait': 'Aguarde',
    'noResults': 'Nenhum resultado',
    'tryAgain': 'Tente novamente',
    'somethingWentWrong': 'Algo deu errado',
    'noConnection': 'Sem conexão',
    'areYouSure': 'Tem certeza?',
    'cannotBeUndone': 'Esta ação não pode ser desfeita',
    'saveChanges': 'Salvar Alterações',
    'discardChanges': 'Descartar Alterações',
    'yes': 'Sim',
    'no': 'Não',
    'ok': 'OK',
    'done': 'Concluído',
    'next': 'Próximo',
    'previous': 'Anterior',
    'back': 'Voltar',
    'continue_': 'Continuar',
    'skip_': 'Pular',
    'select': 'Selecionar',
    'selectDate': 'Selecionar data',
    'selectTime': 'Selecionar hora',
    'date': 'Data',
    'time': 'Hora',
    'more': 'Mais',
    'home': 'Home',
    'log': 'Log',
    'insights': 'Insights',
    'calendar': 'Calendário',
    'agenda': 'Agenda',
    'news': 'Notícias',
    'article': 'Artigo',
    'readMore': 'Ler mais',
    'favorite': 'Favorito',
    'favorites': 'Favoritos',
    'recent': 'Recente',
    'popular': 'Popular',
    'featured': 'Destaque',
    'seeAll': 'Ver todos',
    'seeMore': 'Ver mais',
    'seeLess': 'Ver menos',
    'showMore': 'Mostrar mais',
    'showLess': 'Mostrar menos',
    'expand': 'Expandir',
    'collapse': 'Recolher',
    'search': 'Buscar',
    'searchHere': 'Pesquisar...',
    'writeHere': 'Escreva aqui...',
    'typeHere': 'Digite aqui...',
    'categoryPersonal': 'Pessoal',
    'categoryWork': 'Trabalho',
    'categoryStudies': 'Estudos',
    'categoryHealth': 'Saúde',
    'categoryHome': 'Casa',
    'categoryOther': 'Outros',
    'categoryLeisure': 'Lazer',
    'categoryExercise': 'Exercício',
    'categoryMeditation': 'Meditação',
    'categoryReading': 'Leitura',
    'categoryNutrition': 'Alimentação',
    'categorySleep': 'Sono',
    'categoryWater': 'Água',
    'categorySocial': 'Social',
    'categoryFamily': 'Família',
    'categoryFinance': 'Finanças',
    'categoryCreativity': 'Criatividade',
    'analytics': 'Análises',
    'report': 'Relatório',
    'reports': 'Relatórios',
    'chart': 'Gráfico',
    'charts': 'Gráficos',
    'trend': 'Tendência',
    'trends': 'Tendências',
    'average': 'Média',
    'total': 'Total',
    'maximum': 'Máximo',
    'minimum': 'Mínimo',
    'followSystemLanguage': 'Seguir idioma do sistema',
    'dailyGoals': 'Metas Diárias',
    'quickAccess': 'Acesso Rápido',
    'recentActivity': 'Atividade Recente',
    'noRecentActivity': 'Sem atividade recente',
    'todayProgress': 'Progresso de Hoje',
    'habitsPending': 'hábitos pendentes',
    'tasksForToday': 'tarefas para hoje',
    'moodNotRecorded': 'Humor não registrado',
    'recordNow': 'Registrar Agora',
    'welcomeBack': 'Bem-vindo de volta!',
    'moreOptions': 'Mais opções',
    'adjustments': 'Ajustes',
  };

  // Gerar ARB files
  final ptArb = <String, dynamic>{'@@locale': 'pt'};
  final enArb = <String, dynamic>{'@@locale': 'en'};

  translations.forEach((enKey, ptValue) {
    ptArb[enKey] = ptValue;
    // Converter chave para inglês (remover camelCase e capitalizar)
    final enValue = enKey
        .replaceAllMapped(RegExp(r'([A-Z])'), (m) => ' \${m.group(1)}')
        .trim()
        .split(' ')
        .map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1).toLowerCase())
        .join(' ')
        .replaceAll('_', '');
    
    // Usar traduções específicas
    final specificEn = {
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'confirm': 'Confirm',
      'close': 'Close',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'thisWeek': 'This Week',
      'thisMonth': 'This Month',
      'goodMorning': 'Good morning',
      'goodAfternoon': 'Good afternoon',
      'goodEvening': 'Good evening',
      'mood': 'Mood',
      'howAreYou': 'How are you?',
      'howAreYouFeeling': 'How are you feeling?',
      'recordMood': 'Record Mood',
      'veryGood': 'Very good',
      'good': 'Good',
      'neutral': 'Neutral',
      'bad': 'Bad',
      'veryBad': 'Very bad',
      'excellent': 'Excellent',
      'great': 'Great',
      'fair': 'Fair',
      'terrible': 'Terrible',
      'happy': 'Happy',
      'sad': 'Sad',
      'anxious': 'Anxious',
      'calm': 'Calm',
      'stressed': 'Stressed',
      'excited': 'Excited',
      'tired': 'Tired',
      'motivated': 'Motivated',
      'bored': 'Bored',
      'relaxed': 'Relaxed',
      'focused': 'Focused',
      'productive': 'Productive',
      'energetic': 'Energetic',
      'sleepy': 'Sleepy',
      'grateful': 'Grateful',
      'habit': 'Habit',
      'habits': 'Habits',
      'newHabit': 'New Habit',
      'createHabit': 'Create Habit',
      'editHabit': 'Edit Habit',
      'streak': 'Streak',
      'record': 'Record',
      'dailyGoal': 'Daily Goal',
      'weeklyGoal': 'Weekly Goal',
      'frequency': 'Frequency',
      'reminder': 'Reminder',
      'reminders': 'Reminders',
      'task': 'Task',
      'tasks': 'Tasks',
      'newTask': 'New Task',
      'createTask': 'Create Task',
      'editTask': 'Edit Task',
      'myTasks': 'My Tasks',
      'noTasks': 'No tasks',
      'noTasksPending': 'No pending tasks',
      'noTasksCompleted': 'No completed tasks',
      'addTaskToStart': 'Add a task to get started',
      'completeTasksToSee': 'Complete your tasks to see them here',
      'taskTitle': 'What do you need to do?',
      'dueDate': 'Due Date',
      'category': 'Category',
      'categories': 'Categories',
      'priority': 'Priority',
      'priorityHigh': 'High',
      'priorityMedium': 'Medium',
      'priorityLow': 'Low',
      'all': 'All',
      'pending': 'Pending',
      'completed': 'Completed',
      'overdue': 'Overdue',
      'note': 'Note',
      'notes': 'Notes',
      'newNote': 'New Note',
      'createNote': 'Create Note',
      'editNote': 'Edit Note',
      'myNotes': 'My Notes',
      'noNotes': 'No notes',
      'quickNote': 'Quick Note',
      'title': 'Title',
      'content': 'Content',
      'description': 'Description',
      'timer': 'Timer',
      'focus': 'Focus',
      'breakTime': 'Break',
      'shortBreak': 'Short Break',
      'longBreak': 'Long Break',
      'start': 'Start',
      'pause': 'Pause',
      'stop': 'Stop',
      'restart': 'Restart',
      'resume': 'Resume',
      'session': 'Session',
      'sessions': 'Sessions',
      'focusTime': 'Focus Time',
      'timerActive': 'Timer Active',
      'inBackground': 'in background',
      'continueInBackground': 'Continue in background',
      'backToTimer': 'Back to timer',
      'endSession': 'End session',
      'pauseTimer': 'Pause timer',
      'activity': 'Activity',
      'activities': 'Activities',
      'history': 'History',
      'statistics': 'Statistics',
      'library': 'Library',
      'book': 'Book',
      'books': 'Books',
      'newBook': 'New Book',
      'addBook': 'Add Book',
      'reading': 'Reading',
      'read': 'Read',
      'wantToRead': 'Want to Read',
      'abandoned': 'Abandoned',
      'author': 'Author',
      'pages': 'Pages',
      'progress': 'Progress',
      'rating': 'Rating',
      'review': 'Review',
      'genre': 'Genre',
      'myBooks': 'My Books',
      'noBooks': 'No books',
      'settings': 'Settings',
      'preferences': 'Preferences',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'automatic': 'Automatic',
      'language': 'Language',
      'notifications': 'Notifications',
      'sounds': 'Sounds',
      'vibration': 'Vibration',
      'backup': 'Backup',
      'restore': 'Restore',
      'account': 'Account',
      'profile': 'Profile',
      'about': 'About',
      'help': 'Help',
      'version': 'Version',
      'rateApp': 'Rate App',
      'privacy': 'Privacy',
      'level': 'Level',
      'points': 'Points',
      'achievement': 'Achievement',
      'achievements': 'Achievements',
      'unlocked': 'Unlocked',
      'locked': 'Locked',
      'success': 'Success',
      'error': 'Error',
      'warning': 'Warning',
      'loading': 'Loading',
      'pleaseWait': 'Please wait',
      'noResults': 'No results',
      'tryAgain': 'Try again',
      'somethingWentWrong': 'Something went wrong',
      'noConnection': 'No connection',
      'areYouSure': 'Are you sure?',
      'cannotBeUndone': 'This action cannot be undone',
      'saveChanges': 'Save Changes',
      'discardChanges': 'Discard Changes',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'done': 'Done',
      'next': 'Next',
      'previous': 'Previous',
      'back': 'Back',
      'continue_': 'Continue',
      'skip_': 'Skip',
      'select': 'Select',
      'selectDate': 'Select date',
      'selectTime': 'Select time',
      'date': 'Date',
      'time': 'Time',
      'more': 'More',
      'home': 'Home',
      'log': 'Log',
      'insights': 'Insights',
      'calendar': 'Calendar',
      'agenda': 'Agenda',
      'news': 'News',
      'article': 'Article',
      'readMore': 'Read more',
      'favorite': 'Favorite',
      'favorites': 'Favorites',
      'recent': 'Recent',
      'popular': 'Popular',
      'featured': 'Featured',
      'seeAll': 'See all',
      'seeMore': 'See more',
      'seeLess': 'See less',
      'showMore': 'Show more',
      'showLess': 'Show less',
      'expand': 'Expand',
      'collapse': 'Collapse',
      'search': 'Search',
      'searchHere': 'Search...',
      'writeHere': 'Write here...',
      'typeHere': 'Type here...',
      'categoryPersonal': 'Personal',
      'categoryWork': 'Work',
      'categoryStudies': 'Studies',
      'categoryHealth': 'Health',
      'categoryHome': 'Home',
      'categoryOther': 'Other',
      'categoryLeisure': 'Leisure',
      'categoryExercise': 'Exercise',
      'categoryMeditation': 'Meditation',
      'categoryReading': 'Reading',
      'categoryNutrition': 'Nutrition',
      'categorySleep': 'Sleep',
      'categoryWater': 'Water',
      'categorySocial': 'Social',
      'categoryFamily': 'Family',
      'categoryFinance': 'Finance',
      'categoryCreativity': 'Creativity',
      'analytics': 'Analytics',
      'report': 'Report',
      'reports': 'Reports',
      'chart': 'Chart',
      'charts': 'Charts',
      'trend': 'Trend',
      'trends': 'Trends',
      'average': 'Average',
      'total': 'Total',
      'maximum': 'Maximum',
      'minimum': 'Minimum',
      'followSystemLanguage': 'Follow system language',
      'dailyGoals': 'Daily Goals',
      'quickAccess': 'Quick Access',
      'recentActivity': 'Recent Activity',
      'noRecentActivity': 'No recent activity',
      'todayProgress': 'Today\'s Progress',
      'habitsPending': 'habits pending',
      'tasksForToday': 'tasks for today',
      'moodNotRecorded': 'Mood not recorded',
      'recordNow': 'Record Now',
      'welcomeBack': 'Welcome back!',
      'moreOptions': 'More options',
      'adjustments': 'Adjustments',
    };
    
    enArb[enKey] = specificEn[enKey] ?? enValue;
  });

  const encoder = JsonEncoder.withIndent('  ');
  
  // Salvar arquivos
  await File('lib/src/localization/app_pt.arb').writeAsString('${encoder.convert(ptArb)}\n');
  await File('lib/src/localization/app_en.arb').writeAsString('${encoder.convert(enArb)}\n');
  
  print('✅ Arquivos ARB gerados com ${translations.length} traduções!');
  print('📝 Próximo: flutter gen-l10n');
}
